#!/bin/bash


read -p "How old are you ? " age


if [ $age -ge 16 ]
then 
  echo "You are Eligible to have a Driver's License"
elif [ $age -eq 15 ]
then
  echo "You are Eligible to have a Driver's License next year"
else
  echo "Don't Drive" 
fi


read -p "Enter the number u wanna check if it is EVEN or not ? " num

if ((num%2 == 0));then
  echo "The Number $num is Even"
else
  echo "The Number $num is Odd"
fi
